version: '3.8'

services:
  db_postgres_preprod:
    image: postgres
    container_name: db_postgres_preprod
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - $PWD/pg_data_preprod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/data

  api_main_preprod:
    container_name: api_main_preprod
    restart: "no"
    build:
      context: $PWD/../api_main
      dockerfile: $PWD/../api_main/Dockerfile.api_main.preprod
    depends_on:
      - "db_postgres_preprod"

    ports:
      - "4000:4000"
    entrypoint:
      - /bin/sh
      - /usr/app/docker-entrypoint_api_main_preprod.sh
    volumes:
      #- $PWD/nginx_preprod:/etc/nginx/templates
      - ./docker-entrypoint_api_main_preprod.sh:/usr/app/docker-entrypoint_api_main_preprod.sh
    environment:
      - PS1=$$(whoami)@api_main_preprod:/
      - PORT=4000
      - NODE_ENV=production
      - NODE_PATH=src
      - DATABASE_PORT=5432
      - DATABASE_HOST=db_postgres_preprod
      - DATABASE_NAME=postgres
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_SCHEMA=public
      - JWT_SECRET=secret
      # command:
      #   [
      #     "./wait-for-postgres.sh",

      #     --
      #   ]
      # npm,
      # run,
      # db-migrate,
      # up,
      # --,
      # "&&",
      # pm2-runtime,
      # src/server.js
      # "--",
      # "pm2-runtime",
      # "src/server.js"
    links:
      - db_postgres_preprod

  web_app_preprod:
    container_name: web_app_preprod
    restart: unless-stopped
    build:
      context: $PWD/../web_app
      dockerfile: $PWD/../web_app/Dockerfile.web_app.preprod
    ports:
      - "8080:8080"
    environment:
      - PS1=$$(whoami)@web_app_preprod:/
      - REACT_APP_GRAPHQL_URI=/graphql
      - REACT_APP_STORAGE_URI=/storage
      - NODE_ENV=production

  nginx_preprod:
    image: nginx
    restart: unless-stopped
    volumes:
      #- $PWD/nginx_preprod:/etc/nginx/templates
      - ./nginx_preprod/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "api_main_preprod"
      - "web_app_preprod"
    ports:
      - "80:80"
    environment:
      # - NGINX_HOST=ztasks.localhost
      - NGINX_PORT=80
