version: '3.8'

services:

  db_postgres_dev:
    container_name: db_postgres_dev
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - $PWD/pg_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/data

  # frontend_gateway:
  #   container_name: frontend_gateway
  #   image: nginx
  #   volumes:
  #     - ./templates:/etc/nginx/templates
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80

  api_main_dev:
    container_name: api-main-dev
    build:
      context: $PWD/../api_main
      dockerfile: $PWD/../api_main/Dockerfile.api_main.dev
    tty: true
    #entrypoint: $PWD/docker-entrypoint_api_main_dev.sh
    ports:
      - "4000:4000"
    volumes:
      - $PWD/../api_main:/usr/src/app
    environment:
      - PS1=${GREEN}$$(whoami)@api_main_dev:${GREEN}
      - PORT=4000
      - NODE_PATH=src
      - DATABASE_NAME=postgres
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_SCHEMA=public
      - JWT_SECRET=secret
